### ISSUE TITLE
cinnamon: Endpoint labels missing for 'Speed' slider in touchpad settings

### ISSUE THREAD

**Issue by kalevsr** [linuxmint/mint21.1-beta#16]
The 'Speed' slider in touchpad settings has both endpoints labelled 'None'. It should be 'Slower' and 'Faster' instead.

If I'm not mistaken, the culprit is line 131 in this file:
[https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_mouse.py](https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_mouse.py)

**Comment by clefebvre** [comment]
Thanks. Fixed by https://github.com/linuxmint/cinnamon/commit/b92a48873a8e5be8309418037cbadbbe85ce6cf3.

PS: You can click on the line number in github and it gives you a link which highlights the line (https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_mouse.py#L131).
