### ISSUE TITLE
PPA : add PPA doesn't work

### ISSUE THREAD

**Issue by letuxmasque** [linuxmint/mint21.1-beta#20]
Added a PPA doesn't work (GUI and CLI). The key is not imported correctly:
![erreur ppa dans mintupdate](https://user-images.githubusercontent.com/36480615/205979578-aeda9f6f-f150-42af-bc57-49e34ca8b973.png)

![erreur ajout ppa cli](https://user-images.githubusercontent.com/36480615/205979636-9c55d10a-b526-4e74-b15c-2fb5641e6eb5.png)

**Comment by mdevansh06** [comment]
This is a problem in mint vanessa as well an ubuntu jammy due to ubuntu migrating to trusted.gpg.d from trusted.gpg. You may need to add the key yourself with ``sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com <missing-key>``. This will add the key to trusted.gpg and apt will still show a warning for ``key stored in legacy trusted.gpg``.
[See here!](https://itsfoss.com/key-is-stored-in-legacy-trusted-gpg/)

**Comment by letuxmasque** [comment]
@mdevansh06 `apt-key` is deprecated. So in Linux Mint 21.1, the way to import the key is changing, and it will be directly import in `/etc/apt/keyrings/` as recommended by [Debian](https://wiki.debian.org/DebianRepository/UseThirdParty). Like that you don't need to import the key manually.
@clefebvre announced in [a blog post](https://blog.linuxmint.com/?p=4408) this change will be backported in vanessa too.

**Comment by callagg2** [comment]
ah glad i wasn't doing anything wrong then, I had this issue also with adding PPAs - even through the Software Sources application.

**Comment by clefebvre** [comment]
Fixed in mintsources 2.2.1

**Comment by mdevansh06** [comment]
Will this affect adding ppa by mintsources only or also fix the issue for add-apt-repository?

**Comment by letuxmasque** [comment]
The tests I have done after upgrade to mintsources 2.2.1 solve the issue on both.

**Comment by callagg2** [comment]
agreed, working fine for me now in Software Sources
