### ISSUE TITLE
artwork: default cursor is too loose

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/mint21.1-beta#24]
The cursor's tip should be always pointy so you know where your click will land on. Bibata Oroginal or even Breeze may help.

**Comment by clefebvre** [comment]
Thanks for the feedback. I think this is quite subjective though. I don't think it's a problem.

I've been using this pointer personally for about a month in preparation for this release and never had that issue.

It's also worth noting it's very easy to switch to an alternative theme if there's a niche audience where this problem arises.

**Comment by Secret-chest** [comment]
Thank you for your kind response. Have a nice day!

**Comment by NintendoManiac64** [comment]
It might be worth mentioning that, since Ubuntu 11.04 (whether via a long-standing "bug" or an intentional feature-change - nobody is quite sure), the "activation" zone for the mouse cursor is one pixel in from the farthest-left (most easily noticed with DMZ-black positioned along the left edge of your screen, or DMZ-white positioned along the right edge of your screen).

It's very possible that this could be part of your issue since it's something that's independent of the cursor and therefore occurs  with Bibata as well.
