### ISSUE TITLE
Can't purge package in mintdrivers

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.1-beta#26]
Purging (in test mode) doesn't work and we're removing. The error (you usually don't see it, neither in the gui nor in terminal, but I modified the code so I saw it): 'Task' object has no attribute 'purge_packages_async'

**Comment by mtwebster** [comment]
What version of packagekit do you have?

Please run:
```
dpkg --list | grep packagekit
```
and
```
apt policy packagekit
```

Did you install from the beta iso or do some sort of upgrade?

**Comment by carlosmintfan** [comment]
I have the vera repo, but not everything or maybe just a little bit is vera, I still have Vanessa stuff!
`ii  gir1.2-packagekitglib-1.0                  1.2.5-2ubuntu2                             amd64        GObject introspection data for the PackageKit GLib library
ii  gstreamer1.0-packagekit                    1.2.5-2ubuntu2                             amd64        GStreamer plugin to install codecs using PackageKit
ii  libpackagekit-glib2-18:amd64               1.2.5-2ubuntu2                             amd64        Library for accessing PackageKit using GLib
ii  packagekit                                 1.2.5-2ubuntu2                             amd64        Provides a package management service
ii  packagekit-tools                           1.2.5-2ubuntu2                             amd64        Provides PackageKit command-line tools
`
`packagekit:
  Installiert:           1.2.5-2ubuntu2
  Installationskandidat: 1.2.5-2ubuntu2mint1+vera
  Versionstabelle:
     1.2.5-2ubuntu2mint1+vera 700
        700 http://packages.linuxmint.com vera/upstream amd64 Packages
 *** 1.2.5-2ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
`
Wait, I'll update it.

**Comment by carlosmintfan** [comment]
And the Driver Manager at least sometimes installs mint-dev-pkg when switching to linux-generic, maybe this is only when doing multiple changes without restarting? You can debug this and open a new issue if you want, but wait, I'll look about the purging...

**Comment by carlosmintfan** [comment]
Okay, thanks!

**Comment by carlosmintfan** [comment]
Reopening. You may look at what I said above with the installing and open a new issue and close this again! :) :)

**Comment by mtwebster** [comment]
I appreciate the effort you're making here but please don't submit any more issues based on an upgraded system.

Your second issue is more than likely also caused by an incomplete upgrade, and I'm not going to spend any time on it unless someone reports it based on a fresh iso install.

This issue tracker is *specifically* for testing the beta iso, and the programs that get installed with it. When you report things like this you only muddy the waters, especially when you don't reveal that you're not running the beta in the first place.

I'd recommend something like virtualbox to create a machine you can install the iso on, if you want to continue testing the beta.
