### ISSUE TITLE
Please reconsider the default colors

### ISSUE THREAD

**Issue by axel358** [linuxmint/mint21.1-beta#28]
Green or Teal should be the default accent color on Mint, i mean  is part of what makes it Linux "Mint" and not anything else. The blue accent color combined with those yellow folders (wich are present on all color variants of the Min Y set) makes Nemo look like Explorer, i don't know if that was what u guys were aiming for but i really hope is not. Please don't take this the wrong way but if i wanted something that looks like Windows i would just use Windows, i guess that also goes for the corner bar. It's hard for me to write these words, and i apologize if they sound a bit harsh but this decision feels rushed.

**Comment by jakoblm** [comment]
I would also briefly contribute something to this. There's no accounting for taste, and you can't please everyone. But I also spontaneously associated the yellow folders with Windows Explorer. Whether you like that is another question. 

However, I liked the old colors very much. Could you consider to offer a possibility to restore the old design from LM 21 "Vanessa"? I know that there are "Mint-Y-Legacy" themes. However, they automatically take over the black sidebar in Nemo. Can I also download the current "Vera Themes" and save them in ~/.themes to continue using them?

**Comment by Duckeenie** [comment]
While were at it we should ditch folders as well since Microsoft use those too.

**Comment by carlosmintfan** [comment]
Please provide "middle legacy" themes that look like 20.3/21

**Comment by NintendoManiac64** [comment]
Even though, for my personal color scheme of choice (teal), I prefer the 20.2 variant, I do still think it's a bit odd to leave out the aforementioned "middle legacy" variants used by 20.3/21.0.

**Comment by Mr-Dead** [comment]
Hello.  

Why op being downvoted like on reddit I do not know.  This ticket may not be in spirit with Top Dev's project readme, but it does state verbatim "to collect feedback."

With that, op is within bounds but lacks good reason.  Here I provide better understanding.  True, Linuxmint not always been green, yes?  Green =/=elegance, yes?  I believe both true, but also both are not reason to deviate from green default.

Mint has impeccable brand with much recognition through the green default.  The logo, the website, the NAME, the 15 years default green folders.  That recognition is capital.  The Mint logo, which green is constant, is highly visible among peers online.  The Cinnamon desktop is renown for uniform experience and smart design in spite of gnome.  Pop could not hang for half the time Mint been at this game.  This green desktop literally says Ubuntu is a flavor of Mint!  These are celebrations for hard work and success, not mere idealism.

Therefore, changes to such staples deserve well reasoned explanation.  [Here it is](https://www.linuxmint.com/rel_vera_cinnamon_whatsnew.php)

> We also switched to Aqua by default. We don't need to look green to be Linux Mint. We're Linux Mint no matter what and we want to use the color that looks the most sexy out of the box.

Azul is sexy but the green seals the brand that makes Mint famous.  Furthermore, haughty language reads as preemptive rebuttal to Mint Lovers that rightfully anticipate explanation for drastic change.  Where is proper explanation?  Why deviate from  such obvious and integral trait of Mint?  This boldness did not manifest during website ~~and forum~~ redesign of late.  Ditto for Elsie.  Yet it manifests now in trivial fashion on minor release of flagship product.  Silly.

**Comment by NintendoManiac64** [comment]
...and, of course, the above comment was downvoted as well.  You know, I never really liked the whole "react" function that's seeped in from social media (no surprise that it happened after Microsoft acquired github).  I much prefer the traditional forum-like commentating where all comments are of equal neutrality to the viewer without external opinions coming into play that can deviate one's opinion and/or cause a pre-conceived viewpoint before reading the content.

----------------------------------------------------------------

Anyway, I always tended to see the default green theme in Mint as like choosing Mario in Mario Kart - I'd argue it's one of the least offensive color choices and works well as a "general default" before the user perhaps decides to venture towards other colors.  For example, while I like the color blue in general, I'm not a fan of the aqua color and lean more towards the dark blue/indigo and teal.

...maybe I should ask my sister who is an professional artist and, historically, wasn't a fan of green hues? (she's definitely less fond of green than blue, though she prefers warmer colors in general)  If even she feels the green is a better default, then that should be a bit of a slam-dunk, and she doesn't even use Linux and therefore has no pre-existing bias.

(the one exception is that the default green can look a bit sickly yellow-ish, almost like a "swamp green" on some older CRT-era monitors for whatever reason, but that should be less and less relevant by the day, so to change it *now* clearly implies that CRT monitors were not part of the reasoning)


Regardless, I feel like I have no skin in the game because I don't use the default green and I *never* liked orangey-yellow color tones (ironically, the exact color tones that my sister likes best), so the new folders are a non-starter for me anyway simply because I don't like such color hues (disclosure: I was fine with the more floreceant yellow folder hue used in Windows 7 and Vista, particularly compared to the less-florescent XP folders and especially compared to Windows 10's more orange-y folders)

**Comment by clefebvre** [comment]
> I would also briefly contribute something to this. There's no accounting for taste, and you can't please everyone. But I also spontaneously associated the yellow folders with Windows Explorer. Whether you like that is another question.
> 
> However, I liked the old colors very much. Could you consider to offer a possibility to restore the old design from LM 21 "Vanessa"? I know that there are "Mint-Y-Legacy" themes. However, they automatically take over the black sidebar in Nemo. Can I also download the current "Vera Themes" and save them in ~/.themes to continue using them?

Yes, you should be able to copy over themes, icons, from /usr/share/ to ~/.local/share. Rename their folder and maybe their name in index.theme, and what they inherit from (to make sure they inherit from each other).

I'm sorry we can't support multiple legacy options. We already started to support the 20.2 look when we changed the grey and the sidebar.

**Comment by clefebvre** [comment]
> Please provide "middle legacy" themes that look like 20.3/21

No. We're already going quite far in legacy support. We can't support every combination.

**Comment by clefebvre** [comment]
> Green or Teal should be the default accent color on Mint, i mean is part of what makes it Linux "Mint" and not anything else. The blue accent color combined with those yellow folders (wich are present on all color variants of the Min Y set) makes Nemo look like Explorer, i don't know if that was what u guys were aiming for but i really hope is not. Please don't take this the wrong way but if i wanted something that looks like Windows i would just use Windows, i guess that also goes for the corner bar. It's hard for me to write these words, and i apologize if they sound a bit harsh but this decision feels rushed.

I understand your opinion. It doesn't sound harsh. I think it represents what part of our audience thinks. It was covered in the new features page because of this.

Although the green helped brand the product it also constrained us greatly. It limited what we could do.

When it comes to Windows, there's no ambition to look like it. But there's also no ambition to look different than it. People who like Windows use Windows, people who don't like don't use it.. it's nothing to do with yellow folders or whether a good idea in Windows is applied in Linux or dismissed just because it comes from there.

We want to make the best desktop. If we start thinking in terms of "we can't do this because we need to be green", or "we can't do this because Windows does it", we're not doing our job. This isn't marketing, it's not branding either. It's important, sure, but not as much as the product itself. If we identify vibrant colors as a plus, we do it. If that leads us to Aqua being a better default most people like, so be it. Think of what most people enjoy, not how it sells Mint to people who don't even use it. Nobody came here because we were green. Well I hope not anyway.

**Comment by mfreeman72** [comment]
> While were at it we should ditch folders as well since Microsoft use those too.

I know you're just being facetious, but folders are an integral part of filesystem structure going back decades throughout all OS's, not a style choice, so your argument is not at all valid.

**Comment by mfreeman72** [comment]
@clefebvre - One thing to think about here is accessibility. The all-yellow icons that can't be individually changed is not kind to those of us with poor eyesight, who have come to rely on the ability to have fully different icon colors (not just a tiny tick-mark in the corner) to denote different folder content. That was a great feature of the 20.x and 21 themes. I know there are always the legacy themes, but will those be replaced with the current new theme when the next new theme comes around a few versions down the road and our eyesight is even worse?

**Comment by axel358** [comment]
@clefebvre i feel honored to have received such a understanding and kind reply from you. I also mantain something similar to a linux DE and i've taken inspiration from other DEs i use, Cinnamon included of course ;), so i understand what u mean by implementing ideas u think are useful, no matter where they come from. The yellow folders well i still don't like em xd, but i acknowledge that comparing Nemo with Explorer just because of that was not fair, so once again i apologize. I also appreciate the fact that whenever u guys make this kind of change u leave a way for people to go back to how things were even if that means putting more work on your shoulders.

**Comment by Duckeenie** [comment]
> > While were at it we should ditch folders as well since Microsoft use those too.
> 
> I know you're just being facetious, but folders are an integral part of filesystem structure going back decades throughout all OS's, not a style choice, so your argument is not at all valid.

My point is that like a myriad of things in Mint they share a similarity with their counterparts in Windows. Why are people getting hung up on the colour yellow? It's not rational.

**Comment by mfreeman72** [comment]
> My point is that like a myriad of things in Mint they share a similarity with their counterparts in Windows. Why are people getting hung up on the colour yellow? It's not rational.

Yeah, people often get hung up on defaults, like colors and such, which is often irrational. For me, though, when it interferes with functionality and accessibility, that's when we have an issue. In this case, I'm not so concerned about the color, as much as losing some of the functionality of being able to set icon colors (more than just a tiny diagonal strip in the corner). For us that has accessibility issues. Some of us in my household have minor eyesight problems (consequence of being 50 and over), and we use folder color as an indicator of the content, so we don't have to strain to read all the icon labels or take up screen space by increasing the font size. It's just easier to find things at a glance when you know it's in a red folder instead of a green (or in this case, yellow) one.

Now, I know there will be the legacy icons. But my concern is, a couple major versions down the road, will the new yellow-only folders become the legacy icons as they change to a different style, and possibly remove the different colored folder icons altogether? Why don't they just make their existing Mint-Y-Yellow icon set and the Mint-Y-Blue theme the default, maybe adjusting them for the brighter colors they want? Aside from the little corner strip, the overall look would be the same, but the functionality and accessibility won't suffer.

**Comment by clefebvre** [comment]
@mfreeman72 Yes, this is a fair point. There's an interesting proposal at https://github.com/linuxmint/mint-y-icons/issues/327. I want to look into it in the future, hopefully for the next release.

I think we can de-couple the color sets available in the icon themes from those available in the GTK themes. This would give us more variety in terms of folders but we need to be careful and think about what that means in terms of integration and tools such as folder-color-switcher. We definitely need time to think of it.

**Comment by NintendoManiac64** [comment]
I just wanted to say that, when I asked my aforementioned professional artists of a sister that has no experience with Linux, as expected, she didn't like the green and leaned towards aqua, but preferred the yellow folders to not.

In other words:

1. aqua + yellow folders
2. green + yellow folders
3. aqua + aqua folders
4. green + green folders

That being said, she did make note that she preferred the lighter grey that is used by the legacy themes for the "favorite applications" on the left side of the applications menu (e.g. where the shutdown button and the like are), and also mentioned that she didn't like the dark sidebar used on the "legacy" themes.

You can view the screenshots I shared with her here:
- https://0x0.st/onii.zip

**Comment by mfreeman72** [comment]
@NintendoManiac64 Most likely this is because what she's used to seeing is the Windows coloration, which is of course yellow folders with aqua, and white or light gray backgrounds. People tend to prefer what they're used to. That said, I do like the overall look of the new folders (especially that they're not plain boring flat, and have some nice shadow effects in them). But I would prefer the ability to make these nice looking folders fully change to whatever color fits my needs, even if the default color is yellow.

**Comment by NintendoManiac64** [comment]
@mfreeman72 She's not so tech unsavvy to not change her OS colors though - she's using a sort of purple-ish magenta for her menu bars and has had this color for years now.  Also, her desktop backgrounds tend to be outer space pictures if that matters.

**Comment by jakoblm** [comment]
@clefebvre: I think it's legitimate that you want to move away from the old mint green. I also like the new aqua color. 
But as has been mentioned here: https://github.com/linuxmint/mint21.1-beta/issues/28#issuecomment-1347597222, the yellow folders are difficult to see for people with problematic eyesight. Isn't a basic principle of Linux Mint Cinnamon to achieve the best possible user experience? A strength has always been innovation combined with possibility to customize the interface to one's needs. 

My suggestion:
1. Remove the colored stripes from the folder icons.
2. Supplementing the yellow folder icons with other color accents to match the theme. 
3. Possibility to assign different colors to all folders or globally assign the same color accent. 
4. One problem here could be that in list view in Nemo the highlighted folders (if they have the same color as the highlight) are hard to see. To increase contrast, it could be handled like Dolphin from the KDE project: a highlighted folder icon automatically changes to a lighter color to stand out from the highlight.
