### ISSUE TITLE
Synaptic Package Manager - right-click context menu doesn't list an option to upgrade package like it does in Xubuntu

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#36]
(this occurs in Cinnamon, Mate, and Xfce but, due to the existence of Xubuntu, is easiest to compare to that using Mint Xfce)

From what I can tell, the only way to manually upgrade a package through Synaptic is to double-click on the given package, but this double-click function also exists on Xubuntu in addition to the seemingly Xubuntu-exclusive context menu entry for upgrading (which, for reference, is present on both Xubuntu 22.04 and 22.10).

[mint.webm](https://user-images.githubusercontent.com/11896003/206603573-3d04c57f-014a-416d-9171-96ac0779bdbc.webm)

[xubuntu.webm](https://user-images.githubusercontent.com/11896003/206603581-4eafd1fa-99e0-4727-8609-49a224f0e407.webm)

**Comment by mtwebster** [comment]
This is deliberate. Mint's update manager is better at handling updates for our purposes (it has additional conditions and rules that we filter updates based upon). The less chance of a *novice* user performing these operations in an unfamiliar program the better.

Anything you can perform in synaptic can be done using the terminal if necessary, and this tends to help make sure people know what they're doing before making changes.

If you must, you can install ubuntu's by running:
```
apt install synaptic=0.90.2build1
```

**Comment by ghost** [comment]
Hi @NintendoManiac64 , I'm not part of the team of Mint but I can tell you that the option is like that by design, Mint has patched Synaptic to prevent that option of upgrade due to previously reported issues on their end, it has been like that for a while

If you wish to "upgrade" package using Synaptic, the workaround would be the following:

* Select the package you wish to upgrade on Synaptic
* Go to Package - Force Version
* you will see the option of changing version of package

*EDIT:* seems like @mtwebster went ahead with another option and part of my explanation

**Comment by NintendoManiac64** [comment]
> This is deliberate. Mint's update manager is better at handling updates for our purposes (it has additional conditions and rules that we filter updates based upon). The less chance of a _novice_ user performing these operations in an unfamiliar program the better.

This confuses me.  Since Mint 21.0, mintUpdate now automatically notifies the user of the existence of updates by default so, in that context, why is it still considered desirable to make it less obvious on how to upgrade packages in Synaptic?
