### ISSUE TITLE
nemo/caja: newly created hidden files/folders are shown as 'untitled'

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#51]
(this only occurs with the combination of Cinnamon+Nemo and/s Cinnamon+Caja, it does not occur with any combination on Mate or Xfce nor with Thunar at all)

Not shown in the video is that the exact same issue also occurs if you create a hidden file instead of a hidden folder (e.g. creating a new file that is named `.test`) while hidden files are not shown.

And, as seen when testing Caja, it seems that the newly-typed file name will be correctly displayed if it results in the folder/file being moved to a different location.

[cinnamon.webm](https://user-images.githubusercontent.com/11896003/206826148-8faa3357-3d16-43eb-b5eb-730a1ae9dbbf.webm)

**Comment by MenthaSuaveolens** [comment]
This issue is also present in Nemo 5.4.3 (LM 21.0 Cinnamon).
Create a hidden folder while "Show Hidden Files" is disabled. The name "untitled" shows up for a very short time. The hidden folder is being displayed as long as one stays into the parent folder. After entering several hidden folders I managed to get an untitled folder. The same problem applies to a hidden file. I created a hidden file .a which was displayed as "untitled"
