### ISSUE TITLE
nemo:  with "Auto-arrange" disabled, deleting /home/<user>/.cache results in misaligned icons when the thumbnails are regenerated (when you log back in)

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#55]
(this only occurs on Cinnamon)

Note that this issue seems to be "additive" as shown in my video in that, if you do it over and over without manually re-aligning your desktop icons, the issue will become worse and worse until icons are eventually overlapping each-other.

[cinnamon desktop cache deletion.webm](https://user-images.githubusercontent.com/11896003/206887431-d9f08707-81ea-4490-9786-0bf547e1cbd1.webm)

**Comment by SebastJava** [comment]
This is not a complex, rare, edge case that can be ignored. Your title and your video suggest this problem only occurs under very special circumstances. No. Look at your video again and this problem occurs before you delete your `~/.cache`. It is a very general, annoying, simple problem. And this is not new. Look here: https://github.com/linuxmint/nemo/issues/2727

NOTE: IMHO, when i say this problem is not new, i don't mean to say it should be ignored !

**Comment by NintendoManiac64** [comment]
It's just that I wanted to put ~/.cache along with /tmp onto a ramdisk, but doing so was causing the issue shown in the video, so...

**Comment by SebastJava** [comment]
to sum up:
![image](https://user-images.githubusercontent.com/31940713/207382195-d3f1df6a-f809-42d5-af18-066710afcdf1.png)
