### ISSUE TITLE
Some Flatpak apps switch to Adwaita (White) after changing the color of new Mint-Y-Dark theme. 

### ISSUE THREAD

**Issue by wolkzel** [linuxmint/mint21.1-beta#61]
Changing the color of new Mint-Y-Dark theme breaks the theme of Lutris and Foliate, after that those apps switch to Adwaita theme. Only selecting green applies the dark theme to these apps, but the color of it isn't vibrant.

https://user-images.githubusercontent.com/46371662/206902469-ddc82194-3180-4c49-bff7-05a4a791347c.mp4

**Comment by anaximeno** [comment]
All flatpak themes are not installed by default, also they seem to be more outdated, looking at the different intensities of the green accent.

**Comment by haggen88** [comment]
I confirm, usually only 'org.gtk.Gtk3theme.Mint-Y-Aqua' or 'org.gtk.Gtk3theme.Mint-Y-Dark-Teal' are downloaded when installing a flatpak app. The issue for dark themes is fixed by installing the other themes.

org.gtk.Gtk3theme.Mint-Y-Dark
org.gtk.Gtk3theme.Mint-Y-Dark-Aqua
org.gtk.Gtk3theme.Mint-Y-Dark-Blue
org.gtk.Gtk3theme.Mint-Y-Dark-Brown
org.gtk.Gtk3theme.Mint-Y-Dark-Grey
org.gtk.Gtk3theme.Mint-Y-Dark-Orange
org.gtk.Gtk3theme.Mint-Y-Dark-Pink
org.gtk.Gtk3theme.Mint-Y-Dark-Purple
org.gtk.Gtk3theme.Mint-Y-Dark-Red
org.gtk.Gtk3theme.Mint-Y-Dark-Sand
org.gtk.Gtk3theme.Mint-Y-Dark-Teal


P.S. Flatpak apps require a restart for color themes to be applied correctly.

**Comment by mtwebster** [comment]
At session start, the mintupdate launcher should check the current theme and download the corresponding flatpak automatically, if it's not already installed.

It should also add the current theme to the required packages when installing any flatpak from the software manager.

There's just no way currently to have it automatically happen on-the-fly.

We'll probably be taking another look at this in the next development cycle, but for now this isn't a blocking issue.

**Comment by mtwebster** [comment]
> All flatpak themes are not installed by default, also they seem to be more outdated, looking at the different intensities of the green accent.

We'll try to get them updated soon.
