### ISSUE TITLE
mintupdate doesn't auto refresh apt packages anymore

### ISSUE THREAD

**Issue by Tibladar** [linuxmint/mint21.1-beta#81]
Previously with LM 21 mintupdate refreshed the apt cache after booting ("Refresh the list of updates automatically").

Now mintupdate (5.9.1) only refreshes the flatpak cache thus apt updates only show up after manually refreshing the cache or after the next update period.

### Steps to reproduce:

- Install LM21.1 Beta
- Boot LM
- Wait 10 minutes (default setting) or set it to 1 minute and reboot
- Mintupdate shows some apt updates (3 in beta ISO)
- Refresh the cache and see much more package updates

**Comment by clefebvre** [comment]
I think it's always been like that. The initial refresh is local only. I just tested that with a 20.3 ISO.

**Comment by clefebvre** [comment]
I can't reproduce. It works fine for me post-install:

![image](https://user-images.githubusercontent.com/1138515/207868153-d70495a1-41af-4739-8171-91d7c42a3aad.png)

**Comment by clefebvre** [comment]
Here it:

- finds 25 updates from the local APT cache.
- waits 1 minute to perform the initial refresh
- does so because the UI is closed (otherwise it gets skipped)
- Check Cinnamon, Flaptpak and APT updates
- Finds 1 update (there's a new mintupdate version, so it only counts 1, but irrelvant of the number, it found new updates from the APT remote repositories).
