### ISSUE TITLE
veractor said: But I still think we should still support the old usage as much as possible, to...

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.1-beta#94]
> to insist that any exec line that includes field codes within quotes must be rewritten as a call to a script without any field codes inside quotes.

That is of course the ideal scenario.

But I still think we should still support the old usage as much as possible, to avoid breaking things. For instance, most of @hitobashira's [60+ actions](https://github.com/linuxmint/mint21.1-beta/issues/8#issuecomment-1352804264) failed because of the changes.

_Originally posted by @veractor in https://github.com/linuxmint/nemo/issues/3138#issuecomment-1355042506_

**Comment by clefebvre** [comment]
Please don't start a new issue for this. We're already aware of it.

What matters the most here is that we're able to support as much as we can, not in terms of legacy actions, but more importantly in terms of different use cases.

There's a catch 22 situation at play because the regression comes from a necessary fix.
